#Spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:8889/aderitoSpringDB
#    username: root
#    password:
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true